# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 549db1c3ba4318f5556d6014b2d46622b5a32a99868bfe048a7f26047c5dce6501d4dd314291634a0fe299f050753e490c77a2cf18a03db317beca89e5867e77

test:
  secret_key_base: e1eade09016479e8f891c666e455ff35abfa715c78bb8a5a2cd750e0e34f5d1b49369150990bbfae1d26ed6b17790a866ce6edb659183decf351835397acc5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
